[project]
name = "trykittai-mcp-server"
version = "0.1.0"
description = "FastMCP server for TryKitt.ai"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.1.1",
    "httpx>=0.25.0",
]
